import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { StoreProvider } from "@/store/StoreProvider";
import Toast from "@/components/Toast";
import Loading from "@/components/Loading.jsx";
import Link from "next/link";
import Edit from "@/components/Edit";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <StoreProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Toast />
          <Loading />
          <aside style={{ margin: "30px 10px" }}>
            <Link href="/">Home</Link>
            <Link href="/post">Post</Link>
            <Link href="/notice">Notice</Link>
            <Link href="/gallery">Gallery</Link>
            <Link href="/batch">Batch</Link>
            <Link href="/student">Student</Link>
            <Link href="/teacher">Teacher</Link>
            <Link href="/event">Event</Link>
            <Link href="/feedback">Give a feedback</Link>
            <Edit model={"feedback"} id={`/dashboard/feedback`} />
          </aside>
          {children}
        </body>
      </StoreProvider>
    </html>
  );
}
